import { useEffect, useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../lib/supabaseClient'
import Navbar from '../../components/Navbar'
import RiskBadge from '../../components/RiskBadge'
import { ChevronDown, ChevronUp, Clock, Thermometer, Heart, Activity, Download, CheckCircle, AlertCircle } from 'lucide-react'

function generatePDF(intake, patientName) {
  const symptoms = Array.isArray(intake.symptoms) ? intake.symptoms.map(s => s.replace(/_/g, ' ')).join(', ') : '–'
  const breakdown = intake.risk_breakdown
    ? Object.entries(intake.risk_breakdown).map(([, { points, reason }]) => `  • ${reason}: +${points}`).join('\n')
    : ''

  const content = `
MEDIINTAKE — PATIENT INTAKE REPORT
=====================================
Generated: ${new Date().toLocaleString('en-IN')}

PATIENT
-------
Name: ${patientName}
Date of Intake: ${new Date(intake.created_at).toLocaleString('en-IN')}

SYMPTOMS
--------
${symptoms}
Severity: ${intake.severity}
Duration: ${intake.duration_hours ? intake.duration_hours + ' hours' : 'Not specified'}

VITALS
------
Temperature: ${intake.temperature ? intake.temperature + ' °C' : 'Not recorded'}
Heart Rate:  ${intake.heart_rate ? intake.heart_rate + ' bpm' : 'Not recorded'}
Blood Pressure: ${intake.bp_systolic ? intake.bp_systolic + '/' + (intake.bp_diastolic || '?') + ' mmHg' : 'Not recorded'}

RISK ASSESSMENT
---------------
Score: ${intake.risk_score} / 100
Level: ${intake.risk_level?.toUpperCase()}

Score Breakdown:
${breakdown}

STATUS
------
${intake.status === 'reviewed' ? 'Reviewed by hospital staff' : 'Pending review'}
${intake.doctor_notes ? '\nDoctor Notes:\n' + intake.doctor_notes : ''}

NOTES
-----
${intake.notes || 'None'}

=====================================
This report is generated by MediIntake.
For medical emergencies call 108.
`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `intake-report-${intake.id.slice(0, 8)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function StatusBadge({ status }) {
  if (status === 'reviewed') return (
    <span className="inline-flex items-center gap-1.5 bg-emerald-500/15 text-emerald-400 border border-emerald-500/25 px-2.5 py-0.5 rounded-full text-xs font-semibold">
      <CheckCircle className="w-3 h-3" /> Reviewed
    </span>
  )
  return (
    <span className="inline-flex items-center gap-1.5 bg-amber-500/15 text-amber-400 border border-amber-500/25 px-2.5 py-0.5 rounded-full text-xs font-semibold">
      <AlertCircle className="w-3 h-3" /> Pending
    </span>
  )
}

function IntakeCard({ intake, patientName }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="card overflow-hidden">
      <button className="w-full p-4 flex items-center justify-between gap-4 hover:bg-slate-800/30 transition-colors" onClick={() => setOpen(!open)}>
        <div className="flex items-center gap-3 text-left">
          <div className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${intake.risk_level === 'high' ? 'bg-red-400' : intake.risk_level === 'medium' ? 'bg-amber-400' : 'bg-emerald-400'} animate-pulse-slow`} />
          <div>
            <p className="text-sm font-medium text-white">
              {Array.isArray(intake.symptoms) ? intake.symptoms.map(s => s.replace(/_/g, ' ')).join(', ') : 'Symptoms recorded'}
            </p>
            <p className="text-xs text-slate-500 mt-0.5">
              {new Date(intake.created_at).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          <StatusBadge status={intake.status} />
          <RiskBadge level={intake.risk_level} score={intake.risk_score} showScore />
          {open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-slate-800 px-4 pb-4 pt-3 space-y-4 animate-fade-in">
          <div className="grid grid-cols-3 gap-3">
            {intake.temperature && <div className="bg-slate-800/50 rounded-xl p-3 flex items-center gap-2"><Thermometer className="w-4 h-4 text-orange-400" /><div><p className="text-xs text-slate-500">Temp</p><p className="text-sm font-semibold text-white">{intake.temperature}°C</p></div></div>}
            {intake.heart_rate && <div className="bg-slate-800/50 rounded-xl p-3 flex items-center gap-2"><Heart className="w-4 h-4 text-red-400" /><div><p className="text-xs text-slate-500">HR</p><p className="text-sm font-semibold text-white">{intake.heart_rate} bpm</p></div></div>}
            {intake.bp_systolic && <div className="bg-slate-800/50 rounded-xl p-3 flex items-center gap-2"><Activity className="w-4 h-4 text-blue-400" /><div><p className="text-xs text-slate-500">BP</p><p className="text-sm font-semibold text-white">{intake.bp_systolic}/{intake.bp_diastolic}</p></div></div>}
          </div>

          {intake.doctor_notes && (
            <div className="bg-teal-500/5 border border-teal-500/20 rounded-xl p-4">
              <p className="text-xs text-teal-400 font-semibold mb-1">Doctor's Notes</p>
              <p className="text-sm text-slate-300">{intake.doctor_notes}</p>
              {intake.reviewed_at && <p className="text-xs text-slate-600 mt-2">Reviewed {new Date(intake.reviewed_at).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</p>}
            </div>
          )}

          {intake.risk_breakdown && Object.keys(intake.risk_breakdown).length > 0 && (
            <div>
              <p className="text-xs text-slate-500 mb-2">Risk Score Breakdown</p>
              <div className="space-y-1.5 bg-slate-800/50 rounded-xl p-3">
                {Object.entries(intake.risk_breakdown).map(([key, { points, reason }]) => (
                  <div key={key} className="flex items-center justify-between text-xs">
                    <span className="text-slate-400 capitalize">{reason}</span>
                    <span className="text-slate-300 font-semibold">+{points}</span>
                  </div>
                ))}
                <div className="border-t border-slate-700 pt-1.5 flex justify-between text-xs font-bold">
                  <span className="text-white">Total</span><span className="text-white">{intake.risk_score}/100</span>
                </div>
              </div>
            </div>
          )}

          {intake.notes && <p className="text-xs text-slate-500 bg-slate-800/50 rounded-xl p-3">{intake.notes}</p>}

          <button onClick={() => generatePDF(intake, patientName)} className="btn-secondary w-full flex items-center justify-center gap-2 py-2.5 text-sm">
            <Download className="w-4 h-4" /> Download Report
          </button>
        </div>
      )}
    </div>
  )
}

export default function IntakeHistory() {
  const { profile } = useAuth()
  const [intakes, setIntakes] = useState([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all')

  useEffect(() => {
    async function load() {
      const { data } = await supabase
        .from('intakes').select('*').eq('patient_id', profile.id).order('created_at', { ascending: false })
      setIntakes(data || [])
      setLoading(false)
    }
    if (profile) load()
  }, [profile])

  const filtered = intakes
    .filter(i => filter === 'all' || (filter === 'reviewed' ? i.status === 'reviewed' : filter === 'pending' ? i.status === 'pending' : i.risk_level === filter))

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
        <div className="flex items-center justify-between mb-6 animate-slide-up">
          <div>
            <h1 className="section-title">My Intake Records</h1>
            <p className="text-slate-400 text-sm mt-1">{intakes.length} total submissions</p>
          </div>
        </div>
        <div className="flex gap-2 mb-6 flex-wrap">
          {['all', 'high', 'medium', 'low', 'pending', 'reviewed'].map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={`px-3.5 py-1.5 rounded-full text-xs font-semibold capitalize border transition-all ${filter === f
                ? f === 'high' ? 'badge-high' : f === 'medium' ? 'badge-medium' : f === 'low' ? 'badge-low'
                  : f === 'reviewed' ? 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300'
                  : f === 'pending' ? 'bg-amber-500/15 border-amber-500/40 text-amber-300'
                  : 'bg-teal-500/15 border-teal-500/40 text-teal-300'
                : 'bg-slate-800/50 border-slate-700 text-slate-400 hover:border-slate-600'}`}>
              {f === 'all' ? 'All' : f}
            </button>
          ))}
        </div>
        {loading ? (
          <div className="card p-10 text-center text-slate-500 text-sm">Loading…</div>
        ) : filtered.length === 0 ? (
          <div className="card p-10 text-center"><Clock className="w-10 h-10 text-slate-700 mx-auto mb-3" /><p className="text-slate-400 font-medium">No intakes found</p></div>
        ) : (
          <div className="space-y-3 animate-stagger">
            {filtered.map(intake => <IntakeCard key={intake.id} intake={intake} patientName={profile?.full_name} />)}
          </div>
        )}
      </main>
    </div>
  )
}
