import { useEffect, useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../lib/supabaseClient'
import Navbar from '../../components/Navbar'
import { CHRONIC_CONDITION_OPTIONS } from '../../lib/riskScoring'
import { InlineSpinner } from '../../components/LoadingSpinner'
import { CheckCircle, Save, Printer } from 'lucide-react'

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown']

export default function MedicalProfile() {
  const { profile } = useAuth()
  const [form, setForm] = useState({ blood_group: '', allergies: '', chronic_conditions: [], current_medications: '', emergency_contact_name: '', emergency_contact_phone: '', emergency_contact_relation: '', past_medical_history: '' })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    async function load() {
      const { data } = await supabase.from('medical_profiles').select('*').eq('patient_id', profile.id).single()
      if (data) setForm({ blood_group: data.blood_group || '', allergies: data.allergies || '', chronic_conditions: data.chronic_conditions || [], current_medications: data.current_medications || '', emergency_contact_name: data.emergency_contact_name || '', emergency_contact_phone: data.emergency_contact_phone || '', emergency_contact_relation: data.emergency_contact_relation || '', past_medical_history: data.past_medical_history || '' })
      setLoading(false)
    }
    if (profile) load()
  }, [profile])

  const toggleCondition = (val) => setForm(f => ({ ...f, chronic_conditions: f.chronic_conditions.includes(val) ? f.chronic_conditions.filter(c => c !== val) : [...f.chronic_conditions, val] }))

  const handleSave = async (e) => {
    e.preventDefault()
    setSaving(true); setError('')
    const { error: err } = await supabase.from('medical_profiles').upsert({ ...form, patient_id: profile.id }, { onConflict: 'patient_id' })
    if (err) setError(err.message)
    else { setSaved(true); setTimeout(() => setSaved(false), 3000) }
    setSaving(false)
  }

  const handlePrint = () => {
    const content = `
MEDIINTAKE — MEDICAL PROFILE
=============================
Patient: ${profile?.full_name}
Age: ${profile?.age || 'N/A'} | Gender: ${profile?.gender || 'N/A'} | Phone: ${profile?.phone || 'N/A'}

BLOOD GROUP: ${form.blood_group || 'Not specified'}

ALLERGIES:
${form.allergies || 'None reported'}

CHRONIC CONDITIONS:
${form.chronic_conditions.length > 0 ? form.chronic_conditions.map(c => '• ' + c.replace(/_/g, ' ')).join('\n') : 'None reported'}

CURRENT MEDICATIONS:
${form.current_medications || 'None reported'}

EMERGENCY CONTACT:
Name: ${form.emergency_contact_name || 'N/A'}
Relation: ${form.emergency_contact_relation || 'N/A'}
Phone: ${form.emergency_contact_phone || 'N/A'}

PAST MEDICAL HISTORY:
${form.past_medical_history || 'None reported'}

=============================
Generated by MediIntake — ${new Date().toLocaleString('en-IN')}
`
    const win = window.open('', '_blank')
    win.document.write(`<pre style="font-family:monospace;padding:20px;font-size:14px;">${content}</pre>`)
    win.document.close()
    win.print()
  }

  if (loading) return <div className="min-h-screen"><Navbar /><div className="flex justify-center items-center h-64"><div className="w-8 h-8 border-2 border-slate-700 border-t-teal-500 rounded-full animate-spin" /></div></div>

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
        <div className="flex items-start justify-between mb-8 animate-slide-up flex-wrap gap-3">
          <div>
            <h1 className="section-title">Medical Profile</h1>
            <p className="text-slate-400 text-sm mt-1">This information is shown to doctors during emergencies.</p>
          </div>
          <button onClick={handlePrint} className="btn-secondary flex items-center gap-2 text-sm">
            <Printer className="w-4 h-4" /> Print / Share
          </button>
        </div>

        {error && <div className="bg-red-500/10 border border-red-500/30 text-red-400 text-sm px-4 py-3 rounded-xl mb-6">{error}</div>}

        <form onSubmit={handleSave} className="space-y-6 animate-stagger">
          <div className="card p-6 space-y-5">
            <h2 className="font-display font-semibold text-white text-base">Basic Medical Information</h2>
            <div>
              <label className="label">Blood Group</label>
              <select className="input" value={form.blood_group} onChange={e => setForm(f => ({ ...f, blood_group: e.target.value }))}>
                <option value="">Select blood group</option>
                {BLOOD_GROUPS.map(bg => <option key={bg} value={bg}>{bg}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Allergies</label>
              <textarea className="input resize-none" rows={3} placeholder="e.g. Penicillin, Peanuts, Latex…" value={form.allergies} onChange={e => setForm(f => ({ ...f, allergies: e.target.value }))} />
            </div>
            <div>
              <label className="label">Current Medications</label>
              <textarea className="input resize-none" rows={3} placeholder="e.g. Metformin 500mg twice daily…" value={form.current_medications} onChange={e => setForm(f => ({ ...f, current_medications: e.target.value }))} />
            </div>
          </div>

          <div className="card p-6">
            <h2 className="font-display font-semibold text-white text-base mb-1">Chronic Conditions</h2>
            <p className="text-xs text-slate-500 mb-4">These are factored into your emergency risk score.</p>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {CHRONIC_CONDITION_OPTIONS.map(({ value, label }) => {
                const selected = form.chronic_conditions.includes(value)
                return (
                  <button key={value} type="button" onClick={() => toggleCondition(value)}
                    className={`flex items-center gap-2 px-3 py-2.5 rounded-xl text-sm font-medium transition-all border ${selected ? 'bg-teal-500/15 border-teal-500/40 text-teal-300' : 'bg-slate-800/50 border-slate-700 text-slate-400 hover:border-slate-600'}`}>
                    <div className={`w-3.5 h-3.5 rounded flex items-center justify-center border flex-shrink-0 ${selected ? 'bg-teal-500 border-teal-500' : 'border-slate-600'}`}>
                      {selected && <CheckCircle className="w-3 h-3 text-slate-950" />}
                    </div>
                    {label}
                  </button>
                )
              })}
            </div>
          </div>

          <div className="card p-6 space-y-4">
            <h2 className="font-display font-semibold text-white text-base">Emergency Contact</h2>
            <div className="grid sm:grid-cols-2 gap-4">
              <div><label className="label">Contact Name</label><input className="input" type="text" placeholder="Jane Doe" value={form.emergency_contact_name} onChange={e => setForm(f => ({ ...f, emergency_contact_name: e.target.value }))} /></div>
              <div><label className="label">Relation</label><input className="input" type="text" placeholder="Spouse, Parent…" value={form.emergency_contact_relation} onChange={e => setForm(f => ({ ...f, emergency_contact_relation: e.target.value }))} /></div>
            </div>
            <div><label className="label">Phone Number</label><input className="input" type="tel" placeholder="+91 9876543210" value={form.emergency_contact_phone} onChange={e => setForm(f => ({ ...f, emergency_contact_phone: e.target.value }))} /></div>
          </div>

          <div className="card p-6">
            <h2 className="font-display font-semibold text-white text-base mb-4">Past Medical History</h2>
            <textarea className="input resize-none" rows={4} placeholder="Previous surgeries, hospitalizations…" value={form.past_medical_history} onChange={e => setForm(f => ({ ...f, past_medical_history: e.target.value }))} />
          </div>

          <button type="submit" className="btn-primary w-full flex items-center justify-center gap-2 py-3" disabled={saving}>
            {saving ? <><InlineSpinner />Saving…</> : saved ? <><CheckCircle className="w-4 h-4" />Saved!</> : <><Save className="w-4 h-4" />Save Medical Profile</>}
          </button>
        </form>
      </main>
    </div>
  )
}
